version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    container_name: mystery-lunch-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: mysterylunchDB
      POSTGRES_USER: mysterylunch
      POSTGRES_PASSWORD: MysteryLunch!L0c4l
    ports:
      - "5432:5432"

  redis:
    image: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
      
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/project'
      - '/project/tmp'
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  mysterylunch-web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:      
      DB_HOST: db
      DB_NAME: mysterylunchDB
      DB_USERNAME: mysterylunch
      DB_PASSWORD: MysteryLunch!L0c4l
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  postgres_data: {}
  redis:
